// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type AnalysisResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Login               string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Date                string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	TotalDuration       int32                  `protobuf:"varint,3,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	GlobalLimitExceeded bool                   `protobuf:"varint,4,opt,name=global_limit_exceeded,json=globalLimitExceeded,proto3" json:"global_limit_exceeded,omitempty"`
	ExceededLimits      []string               `protobuf:"bytes,5,rep,name=exceeded_limits,json=exceededLimits,proto3" json:"exceeded_limits,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AnalysisResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AnalysisResponse) GetTotalDuration() int32 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *AnalysisResponse) GetGlobalLimitExceeded() bool {
	if x != nil {
		return x.GlobalLimitExceeded
	}
	return false
}

func (x *AnalysisResponse) GetExceededLimits() []string {
	if x != nil {
		return x.ExceededLimits
	}
	return nil
}

var File_proto_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analysis.proto\x12\banalysis\"&\n" +
	"\x0eAnalyzeRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"\xc0\x01\n" +
	"\x10AnalysisResponse\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12%\n" +
	"\x0etotal_duration\x18\x03 \x01(\x05R\rtotalDuration\x122\n" +
	"\x15global_limit_exceeded\x18\x04 \x01(\bR\x13globalLimitExceeded\x12'\n" +
	"\x0fexceeded_limits\x18\x05 \x03(\tR\x0eexceededLimits2V\n" +
	"\x0fAnalysisService\x12C\n" +
	"\vAnalyzeUser\x12\x18.analysis.AnalyzeRequest\x1a\x1a.analysis.AnalysisResponseB\x1bZ\x19grpc-analysis/proto;protob\x06proto3"

var (
	file_proto_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_proto_rawDescData []byte
)

func file_proto_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_proto_rawDescData
}

var file_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analysis_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),   // 0: analysis.AnalyzeRequest
	(*AnalysisResponse)(nil), // 1: analysis.AnalysisResponse
}
var file_proto_analysis_proto_depIdxs = []int32{
	0, // 0: analysis.AnalysisService.AnalyzeUser:input_type -> analysis.AnalyzeRequest
	1, // 1: analysis.AnalysisService.AnalyzeUser:output_type -> analysis.AnalysisResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analysis_proto_init() }
func file_proto_analysis_proto_init() {
	if File_proto_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_proto_depIdxs,
		MessageInfos:      file_proto_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_proto = out.File
	file_proto_analysis_proto_goTypes = nil
	file_proto_analysis_proto_depIdxs = nil
}
